name: build-master
on:
      push:
        paths-ignore:
          - 'docs/**'
        branches:
          - main
jobs:
  check-unix-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - uses: jwlawson/actions-setup-cmake@v1.9
        with:
          cmake-version: '3.20.x'
      - run: |
          pip install gcovr
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key 2>/dev/null | sudo apt-key add -
          sudo add-apt-repository 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-12 main' -y
          sudo apt-get update -q
          sudo apt-get install -y build-essential clang-11 lld-11 libc++-11-dev libc++abi-11-dev clang-tools-11 python libgl-dev 
          sudo pip3 install wheel setuptools conan
          export CC=/usr/bin/clang
          export CXX=/usr/bin/clang++
          cd $GITHUB_WORKSPACE 
          mkdir build && cd build && conan install .. -s cppstd=gnu17 -pr=../conan_profile
          cmake ..
          make -j 4
          bin/tests
          cd CMakeFiles/tests.dir/tests
          gcovr -r ../../../../ . --output coverage.json --coveralls
      - uses: codecov/codecov-action@v1
        with:
            token: 4837ea79-b0b6-49e7-acef-07625b4d7c28 # not required for public repos
            flags: unittests # optional
            name: unit-tests # optional
            fail_ci_if_error: true 
            verbose: true 
