name: build-master
on:
      push:
        paths-ignore:
          - 'docs/**'
        branches:
          - main
jobs:
  check-unix-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - uses: jwlawson/actions-setup-cmake@v1.9
        with:
          cmake-version: '3.20.x'
      - run: |
          pip install gcovr
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key 2>/dev/null | sudo apt-key add -
          sudo apt-get update -q
          sudo apt-get install -y build-essential python libgl-dev 
          sudo pip3 install wheel setuptools conan
          cd $GITHUB_WORKSPACE 
          mkdir build && cd build && conan install .. -pr=../conan_profile
          cmake ..
          make -j 4
          bin/tests
          cd CMakeFiles/tests.dir/tests
          gcov main.cxx.gcda --branch-counts --branch-probabilities --preserve-paths
          ls -la
      - uses: codecov/codecov-action@v1
        with:
            token: 4837ea79-b0b6-49e7-acef-07625b4d7c28 # not required for public repos
            flags: unittests # optional
            name: unit-tests # optional
            fail_ci_if_error: true 
            verbose: false 
